#!/usr/bin/env bash
# install nginx web server

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy

str="\nfrontend http_web\n\tbind *:80\n\tstats url /haproxy?stats\n\tdefault_backend custom_backend\n\nbackend cusom_backend\n\tbalance roundrobin\n\tserver strat 35.231.1.112:80 check\n\tserver web02 54.167.91.234:80 check"
sudo echo -e $str >> /etc/haproxy/haproxy.cfg
