#!/usr/bin/env bash
# write holberton school 10 times but 9th says hi
END=0
x=$END
while [ $x -lt 10 ]
do
    if [ $x -eq 9 ]
    then
        echo Hi
    fi
        echo Holberton School
        x=$((x+1))
done
