#!/usr/bin/env bash
#loop 10 times and display at certain intervals
END=0
x=$END
while [ $x -lt 10 ]
do
    if [ $x -eq 7 ]
    then
        echo good luck
    elif [ $x -eq 3 ]
    then
        echo bad luck
    else
        echo Holberton School
    fi
        x=$((x+1))
done
