#!/usr/bin/env bash
# loop 20 times and print with a case statement
END=0
counter=$END
while [ $counter -lt 21 ]
do
    echo "$counter"
    case $counter in
    4)
        echo bad luck from China
        ;;
  
    9)
        echo bad luck from Japan
        ;;
    17)
        echo bad luck from Italy
        ;;
    esac
        counter=$((counter+1))
done
