#!/usr/bin/env bash
# bash script that gives info

# if file exists holberton file exists
# else holbertonschool file does not exist
# if file exists print (check empty/not empty)
# regular file or nothing
FILE="holbertonschool"

if [ -e "$FILE" ]; then
    echo "$FILE file exists"

    if [ -s "$FILE" ]; then
        echo "$FILE file is not empty"
    elif [ ! -s "$FILE" ]; then
        echo "$FILE file is empty"
    fi

    if [ -f "$FILE" ]; then
        echo "$FILE is a regular file"
    fi
else
    echo "holbertonschool file does not exist"
fi
